---
title: "ageanalysis20.Rmd"
author: "Renuka"
date: "12/10/2020"
output: html_document
---


```{r alpha, message=F, echo=F, echo=FALSE}
library(knitr)
library(knitcitations)
library(microbiome)
library(phyloseq)
library(ggplot2)
library(reshape2)
library(tidyverse)
library(dada2)
library(dplyr)
theme_set(theme_bw(20))
knitr::opts_chunk$set(fig.width=10, fig.height=10, message=FALSE, warning=FALSE)

phyage<- readRDS("D:/sparc/manuscript/phyage.RDS")

```
# Alpha diversity analysis

```{r alpha1, echo=FALSE, message=FALSE, warning=FALSE}
library(microbiome)
opts_chunk$set(dev="CairoPNG")

# Estimate alpha diversities
A <- alpha(phyage)
index <- "diversity_shannon"

# I removed this - no need to show diversities for individual samples. / LL
# kable(head(A))
```


# Group-wise comparisons
* Diversity index: `r index`

```{r group_comp, echo=FALSE, echo=FALSE, message=FALSE, fig.width=10, fig.height=8, fig.show="keep", out.width="50%"}
df <- meta(phyage)
df <- bind_cols(df, A)
df$index <- df[[index]]

# We use Wilcoxon test for two-group comparisons
pv <- wilcox.test(data = df, index ~ factor(Age))$p.value

library(ggbeeswarm)
p1 <- ggplot(df, aes(x = Age, y = index, fill = Age)) +
        ggbeeswarm::geom_beeswarm() +
	theme(axis.text.x = element_text(angle = 0, hjust = 1)) +
        labs(y = "Shannon Diversity",
	     x = "",
	     title = paste0("Wilcoxon test p=", round(pv, 2)))

print(p1)

p2 <- ggplot(df, aes(fill = Age, x = index)) +
        geom_histogram(alpha = 0.5, position = "dodge") +
	labs(x = "Shannon Diversity", y = "Density")
print(p2)

```







#Ordination

```{r init, echo=FALSE, message=FALSE}
library(microbiome)
library(phyloseq)
library(vegan)
opts_chunk$set(dev="CairoPNG")
method <- "PCoA"
trans <- "compositional"
distance <- "jaccard"
```

## *Principal Coordinates Analysis (PCoA)*

* Ordination method: `r method`
* Dissimilarity measure: `r distance`

```{r pcoa, echo=FALSE, message=FALSE, fig.width=9, fig.height=5, out.width="50%", fig.show="hold"}
theme_set(theme_bw(15))
library(microbiome)
p <- plot_landscape(microbiome::transform(phyage , "compositional"),
                    distance = "jaccard",
                    method = "PCoA",
                    size = 3,
                    col = "Age",
                    shading = FALSE) +
  scale_colour_brewer(palette = "Set1")		    
print(p)
```

## DESeq2 analysis



```{r DESeq2, echo=FALSE, message=FALSE, fig.width=5, fig.height=5, out.width="25%", fig.show="hold"}
library(phyloseq)
library(reshape2)
library(DESeq2)

# LL: this is a local path. Can you change this into a path that is not
# system specific. Use for instance: "data/sparc/manuscript/affinlUnr.RDS"
#phyage <- readRDS("data/sparc/manuscript/phyage.RDS")

padj.th <- 0.25
mypseq <- phyage

# Remove NAs
group <- "Age"
keep <- meta(phyage)[, group] %>% complete.cases()

df <- meta(mypseq)[keep, ]

mygroup <- "Age"
df$group <- as.factor(df[[group]] == mygroup)
sample_data(mypseq) <- sample_data(df)
quiet(ds2 <- phyloseq_to_deseq2(mypseq, ~ Age))
dds <- DESeq(ds2)
res <- results(dds)
df <- as.data.frame(res)
df$taxon <- rownames(df)
df <- df %>% arrange(desc(abs(log2FoldChange)), padj) %>%
             filter(padj < padj.th) 

library(knitr)
kable(df)

# Pick the top DEseq2 taxa
top.taxa <- as.character(df$taxon)
df <- meta(phyage)
ps <- microbiome::transform(phyage, "clr")
for (tax in top.taxa) {
  df$taxa <- abundances(ps)[tax, ]
  p <- ggplot(df, aes(x = Age, y = taxa)) +
    geom_boxplot() +
    ggbeeswarm::geom_beeswarm() +    
    theme(axis.text.x = element_text(angle = 360, hjust = 1)) +
    labs(x = "age", y = "Abundance", title = tax)
  print(p)
}
```
