---
title: "ageanalysis"
author: "Renuka"
date: "20 October 2020"
output: html_document
---



```{r alpha, message=F, echo=F, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(phyloseq)
library(dada2)
library(readxl)
library(dplyr)
library(knitr)
library(knitcitations)
library(microbiome)
library(phyloseq)
library(ggplot2)
library(reshape2)
library(tidyverse)
library(dada2)
library(dplyr)
theme_set(theme_bw(20))
knitr::opts_chunk$set(fig.width=10, fig.height=10, message=FALSE, warning=FALSE)

# Was created with: source("create_phyloseq.R")
phy<- readRDS("data/processed/phyloseq/phy20.1.RDS")
Remove <- c("I1", "I2", "I6", "I9", "I10", "I11", "I16", "I19", "I22", "I25", "I27","I28", "I29", "I31","I34", "I40")
subset_samples(phy20.1, Sample %in% Remove)
Q <- subset_samples(phy, !(Sample %in% Remove))
```
# Alpha diversity analysis

```{r alpha1, echo=FALSE, message=FALSE, warning=FALSE}
library(microbiome)
opts_chunk$set(dev="CairoPNG")

# Estimate alpha diversities
A <- alpha(Q)
index <- "diversity_shannon"
```

# Group-wise comparisons
* Diversity index: `r index`

```{r group_comp, echo=FALSE, echo=FALSE, message=FALSE, fig.width=10, fig.height=8, fig.show="keep", out.width="50%"}
library(Cairo)
df <- meta(Q)
df <- bind_cols(df, A)
df$index <- df[[index]]
pv <- wilcox.test(data = df, index ~ factor(Age))$p.value
library(ggbeeswarm)
p1 <- ggplot(df, aes(x = Age, y = index, fill = Age)) +
        ggbeeswarm::geom_beeswarm() +
	theme(axis.text.x = element_text(angle = 0, hjust = 1)) +
        labs(y = "Shannon Diversity",
	     x = "",
	     title = paste0("Wilcoxon test p=", round(pv, 2)))

print(p1)
```


# Ordination

```{r init, echo=FALSE, message=FALSE}
library(microbiome)
library(phyloseq)
library(vegan)
opts_chunk$set(dev="CairoPNG")
method <- "PCoA"
trans <- "compositional"
distance <- "jaccard"
```

## *Principal Coordinates Analysis (PCoA)*

* Ordination method: `r method`
* Dissimilarity measure: `r distance`

```{r pcoa, echo=FALSE, message=FALSE, fig.width=9, fig.height=5, out.width="50%", fig.show="hold"}
theme_set(theme_bw(15))
library(microbiome)
p <- plot_landscape(microbiome::transform(Q , "compositional"),
                    distance = "jaccard",
                    method = "PCoA",
                    size = 3,
                    col = "Age",
                    shading = FALSE) +
  scale_colour_brewer(palette = "Set1")		    
print(p)
```

```{r DESeq2, echo=FALSE, message=FALSE, fig.width=9, fig.height=5, out.width="50%", fig.show="hold"}
library(phyloseq)
library(reshape2)
library(DESeq2)
padj.th <- 0.25
mypseq <- Q

# Remove NAs
group <- "Age"
keep <- meta(Q)[, group] %>% complete.cases()

df <- meta(mypseq)[keep, ]

mygroup <- "Age"
df$group <- as.factor(df[[group]] == mygroup)
sample_data(mypseq) <- sample_data(df)
quiet(ds2 <- phyloseq_to_deseq2(mypseq, ~ Age))
dds <- DESeq(ds2)
res <- results(dds)
df <- as.data.frame(res)
df$taxon <- rownames(df)
#df <- df %>% arrange(desc(abs(log2FoldChange)), padj) %>%
#             filter(padj < padj.th) 
df <- df %>% arrange(padj, desc(abs(log2FoldChange))) %>%
             filter(padj < padj.th) 
df <- subset(df, select= c(log2FoldChange, padj, taxon))
rownames(df) <- NULL

# WHat is the purpose of this one?
#full.names <- apply(tax_table(Q), 1, function (x) {paste(x, collapse = "_")})
# top.taxa <- as.character(df$taxon)
# Add full phylogenetic name for this OTU
df$full_name <- full.names[df$taxon]

library(knitr)
kable(df)


df <- meta(Q)
ps <- microbiome::transform(Q, "clr")
for (tax in top.taxa) {
  df$taxa <- abundances(ps)[tax, ]
  p <- ggplot(df, aes(x = Age, y = taxa)) +
    geom_boxplot() + 
    ggbeeswarm::geom_beeswarm() +
    theme(axis.text.x = element_text(angle = 360, hjust = 1)) +
    labs(x = "Age", y = "Abundance", title = tax)
  print(p)
}
```

#PERMANOVA analysis
```{r PERMANOVA}
library(microbiome)
library(ggplot2)
library(dplyr)

pseq <- Q
data = microbiome::meta(Q)
# Pick relative abundances (compositional) and sample metadata 
pseq.rel <- microbiome::transform(pseq, "compositional")
otu <- abundances(pseq.rel)
meta <- meta(pseq.rel)
library(vegan)
library(phyloseq)
permanova <- adonis(t(otu) ~ Age,
               data = meta(Q), permutations=99, method = "bray")

# P-value
print(as.data.frame(permanova$aov.tab)["Age", "Pr(>F)"])

dist <- vegdist(t(otu))
anova(betadisper(dist, meta$Age))
```

# Investigate the top factors

```{r top_factors}
library(vegan)
coef <- coefficients(permanova)["Age1", ]
top.coef <- coef[rev(order(abs(coef)))[1:20]]
names(top.coef) <- full.names[names(top.coef)]
par(mar = c(3, 14, 2, 1))
barplot(sort(top.coef), horiz = T, las = 1, main = "Top taxa / 1")
```
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
