# Diet Analysis

```{r alpha, message=F, echo=F, echo=FALSE, warning=FALSE }
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(phyloseq)
library(dada2)
library(readxl)
library(dplyr)
library(knitr)
library(knitcitations)
library(microbiome)
library(phyloseq)
library(ggplot2)
library(reshape2)
library(tidyverse)
library(dada2)
library(dplyr)
theme_set(theme_bw(20))
knitr::opts_chunk$set(fig.width=10, fig.height=10, message=FALSE, warning=FALSE)
knitr::opts_chunk$set(fig.path="figure_diet/")

# Was created with: source("create_phyloseq.R")
phy <- readRDS("data/processed/phyloseq/phy20.1.RDS")
```

# Alpha diversity analysis

```{r alpha1, echo=FALSE, message=FALSE, warning=FALSE}
library(microbiome)
opts_chunk$set(dev="CairoPNG")

# Estimate alpha diversities
A <- alpha(phy)
index <- "diversity_shannon"
head(A)
t <- meta(phy)
t2 <- bind_cols(t,A)
is.data.frame(t) 
is.data.frame(t2)
s <- sapply(split(t2$diversity_shannon, t2$Diet), mean) 
g <- sapply(split(t2$diversity_shannon, t2$Diet), sd) 
y <- cbind(s,g)
kable(y)
```


# Group-wise comparisons
* Diversity index: `r index`

```{r group_comp, echo=FALSE, message=FALSE, warning=FALSE, fig.width=6, fig.height=6, fig.show="keep", out.width="50%"}
theme_set(theme_bw(base_size = 25))
library(Cairo)
df <- meta(phy)
df <- bind_cols(df, A)
df$index <- df[[index]]
pv <- wilcox.test(data = df, index ~ factor(Diet))$p.value
wilcox.test(data = df, index ~factor(Diet))

library(ggbeeswarm)
p1 <- ggplot(df, aes(x = Diet, y = index)) +
        geom_boxplot() +
       geom_jitter(width = 0.05) +
	theme(axis.text.x = element_text(angle = 0, hjust = 1)) +theme(legend.position = "none")+
        labs(y = "Shannon Diversity",
	     x = "",
	     title = "Diet")

print(p1)
```

# Ordination

```{r init, echo=FALSE, message=FALSE, warning=FALSE}
library(microbiome)
library(phyloseq)
library(vegan)
opts_chunk$set(dev="CairoPNG")
method <- "PCoA"
trans <- "compositional"
distance <- "bray"
```

## *Principal Coordinates Analysis (PCoA)*

* Ordination method: `r method`
* Dissimilarity measure: `r distance`

```{r pcoa, echo=FALSE, message=FALSE, warning=FALSE, fig.width=7, fig.height=5, out.width="50%", fig.show="hold"}
theme_set(theme_bw(base_size=25))
library(microbiome)
p <- plot_landscape(microbiome::transform(phy , "compositional"),
                    distance = "bray",
                    method = "PCoA",
                    size = 3,
                    col = "Diet",
                    shading = FALSE) +
  scale_colour_brewer(palette = "Set1")	+labs(title = "Diet")	    
print(p)
#p + guides(color = guide_legend(title = "Diet"))"
```


# PERMANOVA analysis

p value for the effect of diet is (p=0.31), which is not significant.

```{r PERMANOVA, echo= FALSE, warning=FALSE}
library(microbiome)
library(ggplot2)
library(dplyr)

pseq <- phy# Rename the example data
data = microbiome::meta(phy)
# Pick relative abundances (compositional) and sample metadata 
pseq.rel <- microbiome::transform(pseq, "compositional")
otu <- abundances(pseq.rel)
meta <- meta(pseq.rel)
library(vegan)
library(phyloseq)
permanova <- adonis(t(otu) ~ Diet,
               data = meta(phy), permutations=99, method = "bray")

# P-value
print(as.data.frame(permanova$aov.tab)["Diet", "Pr(>F)"])

dist <- vegdist(t(otu))
anova(betadisper(dist, meta$Diet))
```

