---
title: "Dirichlet multinominal analysis"
author: "Renuka"
date: "`r Sys.Date()`"
output: html_document
---



```{r init, echo=FALSE, message=FALSE, warning=FALSE}
library(microbiome)
library(DirichletMultinomial)
library(reshape2)
library(magrittr)
library(dplyr)
library(knitr)
phy <- readRDS("data/processed/phyloseq/phy20.1.RDS")
# data(phy) -> this was to load other example data; not needed as you just loaded phy above
pseq <- phy

# Include only those groups that exceed certain abundance and prevalenec
pseq.comp <- microbiome::transform(pseq, "compositional")

theme_set(theme_bw(20))
knitr::opts_chunk$set(fig.width=10, fig.height=10, message=FALSE, warning=FALSE)
opts_chunk$set(dev="CairoPNG")

# Set this to make sure that the figures of this Rmd file get their own name
knitr::opts_chunk$set(fig.path="figure_DMM/")

#det.th <- 0.1/100
det.th <- 0.1/100
prev.th <- 10/100
taxa <- core_members(pseq.comp, detection = det.th, prevalence = prev.th)
pseq <- prune_taxa(taxa, pseq)

dat <- abundances(pseq)
count <- as.matrix(t(dat))
```

Altogether `r length(taxa)` taxonomic groups are detected with `r 100 * prev.th`% prevalence at `r 100 * det.th`% relative abundance. We used this set to determine the community types.




```{r nclusters, echo=FALSE, message=FALSE, warning=FALSE}
# Define here the max (possible) number of clusters. The higher it is, the slower the computing.
max.clusters <- 5
quiet(fit <- lapply(1:max.clusters, dmn, count = count, verbose=TRUE))

lplc <- sapply(fit, laplace) 
aic  <- sapply(fit, AIC) 
bic  <- sapply(fit, BIC)

best <- fit[[which.min(unlist(lplc))]]
# mixturewt(best)
```

The optimal number of clusters is: `r which.min(unlist(lplc))`

The (main) drivers per component are visualized.


```{r DMM, out.width="100%", echo=FALSE, message=FALSE, warning=FALSE, fig.show="hold", fig.width=20, fig.height=10}
ass <- apply(mixture(best), 1, which.max)

full.names <- apply(tax_table(phy), 1, function (x) {paste(x, collapse = "_")})

for (k in seq(ncol(fitted(best)))) {

  d <- melt(fitted(best))
  colnames(d) <- c("OTU", "cluster", "value")
  
  d <- subset(d, cluster == k) %>%
    # Arrange OTUs by assignment strength
    arrange(value) %>%
    mutate(OTU = factor(OTU, levels = unique(OTU))) %>%
    # Only show the most important drivers
    filter(abs(value) > quantile(abs(value), 0.8))     

  # Add full names
  d$full_name <- gsub("Bacteria_", "", full.names[d$OTU])

  p <- ggplot(d, aes(x = full_name, y = value)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    labs(title = paste("Top drivers: community type", k))
    
  print(p)

}  
```

